### PR TITLE
Feat: Solana Improvement Documents

### LINKED ISSUE #77: [Feature Request]: SIMD UI
### Problem
As a developer, I want to stay updated with the [network improvement proposals](https://github.com/solana-foundation/solana-improvement-documents).

### Solution
SolDev should have a section where any developer can find all the proposals and get all the required information (e.g., link to the conversation, proposal description, etc.)

The Solana Foundation [has a repository](https://github.com/solana-foundation/solana-improvement-documents) where this information is being organized. When a PR is merged, the improvement proposal is approved. 

This SIMD is a new thing in Solana; the easiest thing to do is to focus on rending the information for the open PRs first and then evolve the section to show approved proposals. 

### TODO: (Italo)
- [ ] Create wireframes

### PR DESCRIPTION
**Pull request by cdhiraj40**
# Description

- Fixes #77  

# Checklist

- [x] I have performed a self-review of my own code.
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] My changes generate no new warnings.

Thanks, @ZYJLiu for the help 🫡

### CODE REVIEW

**Comment by jacobcreech** [comment]
https://soldev-a3r1yvo3h-ironforge-cloud.vercel.app/simd/405e8761ed2badf670bb6c3acff97bc267c6fce4 Seems like mermaid diagrams are not rendering properly

**Comment by jamesrp13** [comment]
Hmmm I wasn't even familiar with mermaid diagrams until just now. We'll have to see if there's a plugin for rendering that. @cdhiraj40 @ZYJLiu any chance you can look into that?

**Comment by jamesrp13** [comment]
@cdhiraj40 @ZYJLiu It would also be really helpful to have some indication of what we're sorting by on the table (e.g. when you click a header and it sorts by that maybe show an up/down arrow based on the direction it's sorting)

**Comment by italoacasas** [comment]
@cdhiraj40 @ZYJLiu can we use the SIMD id (e.g. 0001) instead of that long id (e.g. 405e8761ed2badf670bb6c3acff97bc267c6fce4) in the URL?

**Comment by italoacasas** [comment]
@cdhiraj40 @ZYJLiu the mermaid issue will probably be solved by adding the remark plugin 

https://github.com/temando/remark-mermaid

**Comment by jamesrp13** [comment]
@italoacasas I'd prefer using the simd id as well but I'm concerned about duplicates since the id isn't automatically assigned

**Comment by italoacasas** [comment]
@jamesrp13 you're right, let's keep it as it is.

**Comment by jamesrp13** [comment]
Documenting here that Italo and I talked about it and decided we should go with simd id + title, e.g. `0001-proposal-title-here` cc @ZYJLiu

**Pull request merged**
